### ISSUE TITLE
Add New Feature: Network Analysis

### ISSUE THREAD

**Issue by aliciafritz** [aliciafritz/Lazy-LinkingIn#1]
Network Analysis: Analyze the network structure to identify key influencers or clusters of connections.

**Comment by willtbso** [comment]
How will "key" be defined? By site posting activity? By number of followers?

**Comment by aliciafritz** [comment]
I think the Python package we will use for this would be NetworkX, which is focused on network analysis and graph theory.

**command to install the package:** $ pip install networkx 
**Link to GitHub for this package:** https://github.com/networkx/networkx
There is an installation doc INSTALL.rst listed there
_*probably need to use pandas too_ 

### **Example of very basic use for the package:**
import networkx 
import pandas
import matplotlib.pyplot

#Create a graph
G = nx.Graph()

#Add nodes
G.add_nodes_from([1, 2, 3, 4])

#Add edges
G.add_edges_from([(1, 2), (2, 3), (3, 4), (4, 1)])

#Visualize the graph
pos = nx.spring_layout(G)  # Set layout for better visualization
nx.draw(G, pos, with_labels=True, font_weight='bold', node_size=700, node_color='skyblue', font_color='black', font_size=10)

#Display the graph
plt.show()

**Comment by willtbso** [comment]
If we show the network structure and make the primary view the number of connections each of our connections has, we would focus on those of our connections that are most connected. We could just set a threshold number, i.e. include those connections with more than 500 connections, or we could do the top 10 or 20 regardless of what the numbers end up being.

**Comment by willtbso** [comment]
Previous idea of connections of connections is not viable in this iteration due to inaccessibility of data from LinkedIn. We can, however, conduct network analysis and visualization by looking at the companies connections work at and the job titles connections have

**Comment by aliciafritz** [comment]
Version 1 of this feature is complete
