### ISSUE TITLE
Add New Feature: Connection Growth Over Time

### ISSUE THREAD

**Issue by aliciafritz** [aliciafritz/Lazy-LinkingIn#2]
Connection Growth Over Time: Plot the growth of your connections over time to visualize your network's expansion.

**Comment by willtbso** [comment]
What characteristics will this depict? Raw number, number by company, by skills, by job titles?

**Comment by aliciafritz** [comment]
I think the python package is Matplotlib/matplotlib.pyplot, which is primarily for data visualization.

Website: https://matplotlib.org/

### **Basic example of code using matplotlib:**
import matplotlib.pyplot as plt

#Sample data
x = [1, 2, 3, 4, 5]
y = [2, 4, 6, 8, 10]

#Create a plot
plt.plot(x, y)

#Add labels and title
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.title('Simple Plot')

#Display the plot
plt.show()

**Comment by aliciafritz** [comment]
Jens finished feature 2
